### ISSUE TITLE
Fix drop shadow

### ISSUE THREAD

**Issue by ahmednfwela** [Azzeccagarbugli/getx_navigation#1]
![image](https://user-images.githubusercontent.com/63286031/125348812-0200c280-e35d-11eb-8fef-d870c4a84f9d.png)

**Comment by Azzeccagarbugli** [comment]
Do you have any idea why this is happening? I even tried to wrap the `Router` widget with a `Material` one and set the `elevation` parameter to `0.0` but nothing changed

**Comment by ahmednfwela** [comment]
Not sure why, but i can't reproduce this on my local machine 
![image](https://user-images.githubusercontent.com/63286031/125349838-50fb2780-e35e-11eb-82cf-81a4f6cdae75.png)

**Comment by Azzeccagarbugli** [comment]
Unfortunately I'm seeing the same result even after the merge with your `PR`, now I just see a new transition effect but the shadow is still there.

I'm running it with `Flutter Stable 2.2.3`

<img width="1408" alt="Screenshot 2021-07-12 at 22 19 04" src="https://user-images.githubusercontent.com/16477661/125350554-2d84ac80-e35f-11eb-9f54-0c6ba059b708.png">

**Comment by ahmednfwela** [comment]
can you do `flutter doctor -v` ?

**Comment by Azzeccagarbugli** [comment]
Ok, I found it. I just added the`transition: Transition.noTransition` on each GetPage and the result is like this now:

<img width="1408" alt="Screenshot 2021-07-12 at 22 23 13" src="https://user-images.githubusercontent.com/16477661/125350944-c1567880-e35f-11eb-83bf-1dce5aa08a48.png">

So as I said before probably depends on this type of animations

**Comment by ahmednfwela** [comment]
yeah I think this is some weird animation caching issue for flutter web

**Comment by Azzeccagarbugli** [comment]
Perfect, maybe we should report this on the main thread as well

**Comment by ahmednfwela** [comment]
what browser is that btw ?

**Comment by ahmednfwela** [comment]
and what OS

**Comment by Azzeccagarbugli** [comment]
```
fvm flutter doctor -v                                                                 
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/azzeccagarbugli/fvm/versions/stable
    • Framework revision f4abaa0735 (11 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/azzeccagarbugli/Library/Android/sdk/
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```

**Comment by ahmednfwela** [comment]
I can confirm this is specific to macos only, since i can't get it on windows

**Comment by Azzeccagarbugli** [comment]
Nice, I do not know simply how to notify also other users about this issue. Maybe we could write it on the documentation of the transitions...

**Comment by ahmednfwela** [comment]
maybe we can write it in the flutter repository, since it's specific to flutter and not getx

**Comment by Azzeccagarbugli** [comment]
Maybe you can start the issue on the Flutter repository and I can add a comment and the screenshot it self. 

Let me know and in case link the issue here! Thanks again for your huge support bro 🙏🏻

**Comment by ahmednfwela** [comment]
I created the issue here: https://github.com/flutter/flutter/issues/86317
Please let me know if you need further help 😄

**Comment by ahmednfwela** [comment]
can you create a minimal repo that's not dependent on getx? Since I can't reproduce it on windows

**Comment by Azzeccagarbugli** [comment]
> can you create a minimal repo that's not dependent on getx? Since I can't reproduce it on windows

I just used the code [here](https://github.com/flutter/flutter/issues/86317#issuecomment-878871215) and there are no problems, the rendering has no strange shadows
